apiVersion: apps/v1
kind: Deployment
metadata:
  name: mirotalk
  labels:
    app: mirotalk
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mirotalk
  template:
    metadata:
      labels:
        app: mirotalk
    spec:
      containers:
        - name: mirotalk
          image: mirotalk/p2p@sha256:2b18182eca59299989b4b86c65c8063cfb55566d4bc9fbdb1b8709b4146fb350
          ports:
            - name: http
              containerPort: 3000
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 1000
            capabilities:
              drop: [ALL]
